sudo: true
language: rust

matrix:
    fast_finish: true
    include:
        - rust: nightly
          env: FEATURES="--features nightly"
        - rust: beta
        - rust: stable
        - rust: 1.8.0
        # verify `const fn`
        - rust: 1.31.0
        # verify wasm32 & js-sys string comparisons
        - rust: stable
          script:
            - rustup target add wasm32-unknown-unknown
            - cargo build --target=wasm32-unknown-unknown

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES

notifications:
    email: false
